config/routes.rb
Rui::Application.routes.draw do  
  resources :responses


  resources :issues do
    resources :responses
  end


  authenticated :user do
    root :to => 'homes#index', as: :authenticated_root
  end
  
  resources :homes
  
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  
  scope "/admin" do
    resources :users
  end  
  
  devise_scope :user do
    root :to => "devise/sessions#new"
  end  
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  STA_CREATED = "created"
  STA_WORKING = "working"
  STA_RESOLVED = "resolved"
  
  belongs_to :user
  belongs_to :resolver, class_name: "User", foreign_key: :resolved_by
  has_many :responses
  
  attr_accessible :description, :status, :title, :user_id, :resolved_by
  validates_presence_of :user_id, :status
  
  before_validation :default_values
  def default_values
    self.status ||= STA_CREATED
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  
  # GET /issues
  # GET /issues.json
  def index
    @issues = get_issues

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @issues }
    end
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    @issue = get_issue

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @issue }
    end
  end

  # GET /issues/new
  # GET /issues/new.json
  def new
    @issue = current_user.issues.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @issue }
    end
  end

  # GET /issues/1/edit
  def edit
    @issue = current_user.issues.find(params[:id])
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = current_user.issues.build(params[:issue])

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render json: @issue, status: :created, location: @issue }
      else
        format.html { render action: "new" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /issues/1
  # PUT /issues/1.json
  def update
    @issue = get_issue

    respond_to do |format|
      if @issue.update_attributes(params[:issue])
        if @issue.status == Issue::STA_RESOLVED
          @issue.update_attribute(:resolved_by, current_user.id)
        end
        
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue = current_user.issues.find(params[:id])
    @issue.destroy

    respond_to do |format|
      format.html { redirect_to issues_url }
      format.json { head :no_content }
    end
  end
  
  private
  def get_issues
    (current_user.has_role?(:admin) or current_user.has_role?(:staff)) ? Issue.all : (current_user.has_role?(:super_user) ? current_user.issues : [])
  end
  
  def get_issue
    (current_user.has_role?(:admin) or current_user.has_role?(:staff)) ? Issue.find(params[:id]) : (current_user.has_role?(:super_user) ? current_user.issues.find(params[:id]) : nil)    
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<%= simple_form_for(@issue, html: {class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title, input_html: {class: "span8 input-xlarge"} %>
    <%= f.input :description, input_html: {class: "span8 input-xlarge", rows: 8} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class=>"btn btn-primary" %>
    <%= link_to 'Back', issues_path, :class=>"btn btn-button" %>
  </div>
<% end %>

app/views/issues/edit.html.erb
<h1>Editing issue</h1>

<%= render 'form' %>

app/views/issues/index.html.erb
<h1>Issues
  <% if can? :create, Issue %>
    <%= link_to 'Create a New Issue', new_issue_path, :class=>"btn btn-primary pull-right" %>
  <% end %>
</h1>

<table class="table table-striped">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Status</th>
    <th>Created At</th>
  </tr>
<% if @issues.empty? %>
  <tr><td colspan="4">There are no issues.</td></tr>
<% end %>
<% @issues.each do |issue| %>
  <tr>
    <td><%= link_to issue.title, issue %></td>
    <td><%= issue.description %></td>
    <td><%= issue.status.capitalize %></td>
    <td><%= issue.created_at.strftime("%m/%d/%Y %I:%M %p") %></td>
  </tr>
<% end %>
</table>

<br />

app/views/issues/new.html.erb
<h1>New issue</h1>

<%= render 'form' %>

app/views/issues/show.html.erb
<p>
  <b>Title:</b>
  <%= @issue.title %>
</p>

<p>
  <b>Description:</b>
  <%= @issue.description %>
</p>
<p>
  <b>Created At:</b>
  <%= @issue.created_at.strftime(AppConfig.time_format) %>
</p>
<p>
  <b>Status:</b>
  <% if @issue.status == Issue::STA_RESOLVED %>
    <%= @issue.status.capitalize %>
  <% else %>
    <% if can? :change_status, Issue %>
      <a href="javascript:;" id="status" data-type="select" data-value="<%= @issue.status %>" data-resource="issue" data-url="<%= issue_path(@issue) %>" data-title="Update Status" data-name="status"><%= @issue.status.capitalize %></a>
    <% else %>
      <%= @issue.status.capitalize %>
    <% end %>
  <% end %>
  
</p>

<% if @issue.status == Issue::STA_RESOLVED %>
<p>
  <b>Resolved by:</b>
  <%= @issue.resolver.username %>
<% end %>

<br/>
<% @issue.responses.each do |response| %>
<div class="panel panel-default">
  <div class="panel-heading">
    <b><%= response.user.username %></b> wrote at <b><%= response.created_at.strftime(AppConfig.time_format) %></b>:
  </div>
  <div class="panel-body">
    <%= response.message %>
  </div>
</div>
<% end %>
<br/>
<div class="panel panel-default">
  <div class="panel-heading">New Response:</div>
  <div class="panel-body">
    <%= simple_form_for([@issue, @issue.responses.build]) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">
        <%= f.input :message, input_html: {class: "span11 input-xlarge", rows: 8} %>
      </div>

      <div class="form-actions">
        <%= f.button :submit, class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>
<% content_for :javascript do %>
<script>
$(document).ready(function(){
  //turn to inline mode
  $.fn.editable.defaults.mode = 'inline';
  
  $('#status').editable({    
    source: <%= raw [Issue::STA_CREATED, Issue::STA_WORKING, Issue::STA_RESOLVED].collect {|x| {value: x, text: x.capitalize}}.to_json %>
  });  
});
</script>
<% end %>