config/routes.rb
Rui::Application.routes.draw do  
  resources :responses


  resources :issues do
    resources :responses
  end


  authenticated :user do
    root :to => 'homes#index', as: :authenticated_root
  end
  
  resources :homes
  
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  
  scope "/admin" do
    resources :users
  end  
  
  devise_scope :user do
    root :to => "devise/sessions#new"
  end  
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  attr_accessor :login
  
  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :username, :name, :email, :password, :password_confirmation, :remember_me  
  attr_accessible :login, :first_name, :last_name
  
  validates_presence_of :username
  validates_format_of :username, with: /^[a-z0-9_]+$/, message: 'must be lowercase alphanumerics only'
  validates_length_of :username, maximum: 32, message: 'exceeds maximum of 32 characters'
  validates_exclusion_of :username, in: ['www', 'mail', 'ftp'], message: 'is not available'
  validates_uniqueness_of :username
  
  after_create :assign_default_role
  
  has_many :issues
  has_many :responses
  
  def full_name
    "#{first_name} #{last_name}"
  end
  
  def assign_default_role
    add_role(:user)
  end
  
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end
  
  def new
    @user = User.new
  end
  
  def create
    authorize! :create, @user, :message => 'Not authorized as an administrator.'
    @user = User.new(params[:user])
    if @user.save
      @user.add_role :user
      redirect_to users_path, :notice => "Successfully created User."
    else
      render :action => 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/dashboard.html.erb
<h1>Dashboard</h1>

app/views/users/index.html.erb
<h3>Users
  <%= link_to "New User", new_user_path, :class=>"btn btn-primary pull-right" %>
</h3>    
<table class="table table-striped">
  <thead>
    <tr>
      <th>Username</th>
      <th>Name</th>
      <th>Email</th>
      <th>Registered</th>
      <th>Role</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.username, user %></td>
      <td><%= user.full_name %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.to_date %></td>
      <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
      <td>
        <% if not user.has_role? :admin %>
          <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
          <%= render user %>
        <% end %>
      </td>
      <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h2>New User</h2>
<%= simple_form_for(@user, :as => "user", :url => users_path, :html => {:class => 'form-vertical' }) do |f| %>
  <%= f.error_notification %>
  <%= display_base_errors @user %>  
  <%= f.input :username, :required => true, :autofocus => true %>
  <%= f.input :email, :required => true %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :password, :required => true %>
  <%= f.input :password_confirmation, :required => true %>
  <%= f.button :submit, 'Create', :class => 'btn-primary' %>
<% end %>

app/views/users/show.html.erb
<h3>User</h3>
<p>Username: <%= @user.username %></p>
<p>Name: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>