config/routes.rb
Rui::Application.routes.draw do  
  resources :responses


  resources :issues do
    resources :responses
  end


  authenticated :user do
    root :to => 'homes#index', as: :authenticated_root
  end
  
  resources :homes
  
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  
  scope "/admin" do
    resources :users
  end  
  
  devise_scope :user do
    root :to => "devise/sessions#new"
  end  
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_filter :authenticate_user!, :set_issue
  load_and_authorize_resource
  
  # GET /responses
  # GET /responses.json
  def index
    @responses = @issue.reponses

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @responses }
    end
  end

  # GET /responses/1
  # GET /responses/1.json
  def show
    @response = @issue.responses.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @response }
    end
  end

  # GET /responses/new
  # GET /responses/new.json
  def new
    @response = @issue.responses.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @response }
    end
  end

  # GET /responses/1/edit
  def edit
    @response = @issue.responses.find(params[:id])
  end

  # POST /responses
  # POST /responses.json
  def create
    @response = @issue.responses.build(params[:response])
    @response.user = current_user
    respond_to do |format|
      if @response.save
        format.html { redirect_to @issue, notice: 'Response was successfully created.' }
        format.json { render json: @response, status: :created, location: @issue }
      else
        format.html { render action: "new" }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /responses/1
  # PUT /responses/1.json
  def update
    @response = @issue.responses.find(params[:id])
    @response.user = current_user
    respond_to do |format|
      if @response.update_attributes(params[:response])
        format.html { redirect_to @response, notice: 'Response was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responses/1
  # DELETE /responses/1.json
  def destroy
    @response = @issue.responses.find(params[:id])
    @response.destroy

    respond_to do |format|
      format.html { redirect_to responses_url }
      format.json { head :no_content }
    end
  end
  
  private
  def set_issue
    @issue = (current_user.has_role?(:admin) or current_user.has_role?(:staff)) ? Issue.find(params[:issue_id]) : (current_user.has_role?(:super_user) ? current_user.issues.find(params[:issue_id]) : nil)
  end
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/responses/_form.html.erb
<%= simple_form_for(@response) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id %>
    <%= f.input :issue_id %>
    <%= f.input :message %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/responses/edit.html.erb
<h1>Editing response</h1>

<%= render 'form' %>

<%= link_to 'Show', @response %> |
<%= link_to 'Back', responses_path %>

app/views/responses/index.html.erb
<h1>Listing responses</h1>

<table>
  <tr>
    <th>User</th>
    <th>Issue</th>
    <th>Message</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @responses.each do |response| %>
  <tr>
    <td><%= response.user_id %></td>
    <td><%= response.issue_id %></td>
    <td><%= response.message %></td>
    <td><%= link_to 'Show', response %></td>
    <td><%= link_to 'Edit', edit_response_path(response) %></td>
    <td><%= link_to 'Destroy', response, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Response', new_response_path %>

app/views/responses/new.html.erb
<h1>New response</h1>

<%= render 'form' %>

<%= link_to 'Back', responses_path %>

app/views/responses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @response.user_id %>
</p>

<p>
  <b>Issue:</b>
  <%= @response.issue_id %>
</p>

<p>
  <b>Message:</b>
  <%= @response.message %>
</p>


<%= link_to 'Edit', edit_response_path(@response) %> |
<%= link_to 'Back', responses_path %>