config/routes.rb
Rui::Application.routes.draw do  
  resources :responses


  resources :issues do
    resources :responses
  end


  authenticated :user do
    root :to => 'homes#index', as: :authenticated_root
  end
  
  resources :homes
  
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  
  scope "/admin" do
    resources :users
  end  
  
  devise_scope :user do
    root :to => "devise/sessions#new"
  end  
end

app/views/layouts/_flash_message.html.erb
<% if not flash.empty? %>
<div id="flash-messages">
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
  	<div class="flash-padding">
	    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
	      <a class="close" data-dismiss="alert">&#215;</a>
	      <%= content_tag :div, raw(msg), :id => "flash_#{name}" %>
	    </div>
	</div>
    <% flash.delete(name) %>
  <% end %>
<% end %>
</div>
<% end %>

app/views/layouts/_head_meta.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><%= content_for?(:title) ? yield(:title) : "Cascade License and Support System" %></title>
<meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Cascade License and Support System" %>">
<link href="/assets/favicon64.png" rel="shortcut icon" type="image/png" />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render "layouts/head_meta" %>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield :head %>  
</head>
<body>
  <div id="wrap">
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="cascade-head">
        <div class="container">
          <h2 class="pull-left">Cascade License and Support System</h2>
          <a class="pull-right" href="/">
            <img src="/assets/logo.png" class="logo">
          </a>
          
        </div>
      </div>
      <div class="navbar-inner">
        <div class="container">
          <button type="button"class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="nav-collapse collapse">
            <% if user_signed_in? %>
            <ul class="nav">
              <li class="<%= menu_active("homes") %>">
                <a href="<%= homes_path %>"><i class="icon-home icon-white"></i> Home</a>
              </li>
              
              <li class="<%= menu_active("issues") %>">
                <a href="<%= issues_path %>"><i class="icon-th-list icon-white"></i> Issues</a>
              </li>              
            </ul>
            <ul class="nav pull-right">
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="javascript:;">
                  Welcome <%= current_user.username %>
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <% if current_user.has_role? :admin %>
                  <li><%= link_to "Manage Users", users_path %></li>
                  <% end %>
                  <li><%= link_to "Sign out", destroy_user_session_path, :method=>:delete %></li>
                </ul>
              </li>
            </ul>
            
            <% else %>
            <ul class="nav">
              <li class="<%= current_page_active(new_user_session_path) %> <%= current_page_active(root_path) %>">
                <a href="<%= new_user_session_path %>">Sign In</a>
              </li>
              <li class="<%= current_page_active(new_user_password_path) %>">
                <a href="<%= new_user_password_path %>">Forgot Password</a>
              </li>
            </ul>
            <% end %>
          </div>
        </div>
      </div>
    </div>  
    <div class="main container">
      <%= render partial: "layouts/flash_message" %>
      <%= yield %>         
    </div>
    <div id="push"></div>
  </div>
  <div id="footer">
    <div class="container">
      <p class="muted credit">&copy; Cascade Technologies, Inc. <%= Date.today.year %></p>
    </div>
  </div>
  <%= yield :javascript %>  
</body>
</html>

app/views/layouts/empty.html.erb
<!DOCTYPE html>
<html>
<head></head>
<body><%= yield %></body>
</html>

app/views/layouts/full_iframe.html.erb
<!DOCTYPE html>
<html>
<head>  
  <%= render "layouts/head_meta" %>
  <%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js", "application" %>
  <style type="text/css">
  html {overflow: auto;}
  html, body, div, iframe {margin: 0px; padding: 0px; height: 100%; border: none;}
  iframe {display: block; width: 100%; border: none; overflow-y: auto; overflow-x: hidden;}
  #logged_in {
    position: fixed;
    right: 20px;
    top: 0px;
    color: #FFFFFF;
    text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25);
    font-family: 'Ubuntu',Tahoma,sans-serif;
    font-size: 14px;
    display: none;
  }
  #logged_in a {
    color: #DD4814;
    text-decoration: none;
  }
  #logged_in a:hover,
  #logged_in a:focus {
    text-decoration: underline;
    color: #DD4814;
  }
  </style>
</head>
<body>
  <% if logged_in? %>
  <div id="logged_in">
    <p>
      Welcome <%= @username %>!&nbsp;|&nbsp;
      <%= link_to "Sign out", signout_path, :method=>:delete, :id=>"signout_link" %>
    </p>
  </div>
  <% end %>
  <%= yield %>  
</body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render "layouts/head_meta" %>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrap">
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">          
          <a class="brand" href="/">CTWI</a>
          <% if logged_in? %>
          <div class="navbar-text pull-right">
            <p>
              Welcome <%= @username %>!&nbsp;|&nbsp;
              <%= link_to "Sign out", signout_path, :method=>:delete %>
            </p>
          </div>
          <% end %>
        </div>
      </div>
    </div>  
    <div class="main container">
      <%= render partial: "layouts/flash_message" %>
      
      <%= yield %>         
    </div>
    <div id="push"></div>
  </div>
  <div id="footer">
    <div class="container">
      <p class="muted credit">&copy; Cascade Technologies, Inc. <%= Date.today.year %></p>
    </div>
  </div>
</body>
</html>

app/views/layouts/no_nav.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render "layouts/head_meta" %>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>  
  <div class="container">
    <%= render partial: "layouts/flash_message" %>
    
    <%= yield %>         
  </div>
  
  <%= yield :javascript %>
</body>
</html>